[package]
name = "location_proof"
type = "bin"
authors = ["GeoPrivacy Team"]
description = "Zero-knowledge location proof circuit"
keywords = ["zk", "location", "proof"]

[dependencies]

[lints]
warnings = "all"

[[bin]]
name = "location_proof"
path = "location_proof.nr"
