name: GeoPrivacy CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Lint Code
      run: npm run lint
    
    # Unit tests for frontend/backend will be added here later if needed

  deployment-check:
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Simulate Deployment
      run: |
        npm ci
        npm run project:validate
        # Placeholder for any non-contract deployment validation

  vercel-deployment:
    needs: [deployment-check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        # zeit-token is deprecated but kept for backward compatibility with older Vercel action versions
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [vercel-deployment]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Install dependencies
      run: npm ci
    
    - name: Compile contracts
      run: npx hardhat compile
    
    - name: Run unit tests
      run: npm run test:contracts
    
    - name: Generate coverage report
      run: npm run test:contracts:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Gas reporter
      run: npm run test:contracts:gas
      env:
        REPORT_GAS: true

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      with:
        solc-version: 0.8.19
        
    - name: Setup Python for Security Scan
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install MythX CLI for Security Scan
      run: pip install mythx-cli
    - name: Run MythX Security Scan
      run: mythx analyze --ci --ci-format github-annotations --api-key ${{ secrets.MYTHX_API_KEY }} --solc-version 0.8.19 ./contracts
